# SMBIOS tables. See https://www.dmtf.org/sites/default/files/standards/documents/DSP0134_3.4.0.pdf

const
    TableSMBIOSDescriptions* = {
        0:   "BIOS Information",
        1:   "System Information",
        2:   "Base Board or Module Information",
        3:   "System Enclosure or Chassis",
        4:   "Processor Information",
        5:   "Memory Controller Information",
        6:   "Memory Module Information",
        7:   "Cache Information",
        8:   "Port Connector Information",
        9:   "System Slots",
        10:  "On Board Devices Information",
        11:  "OEM Strings",
        12:  "System Configuration Options",
        13:  "BIOS Language Information",
        14:  "Group Associations",
        15:  "System Event Log",
        16:  "Physical Memory Array",
        17:  "Memory Device",
        18:  "32-bit Memory Error Information",
        19:  "Memory Array Mapped Address",
        20:  "Memory Device Mapped Address",
        21:  "Built-in Pointing Device",
        22:  "Portable Battery",
        23:  "System Reset",
        24:  "Hardware Security",
        25:  "System Power Controls",
        26:  "Voltage Probe",
        27:  "Cooling Device",
        28:  "Temperature Probe",
        29:  "Electrical Current Probe",
        30:  "Out-of-Band Remote Access",
        31:  "Boot Integrity Services",
        32:  "System Boot Information",
        33:  "64-bit Memory Error Information",
        34:  "Management Device",
        35:  "Management Device Component",
        36:  "Management Device Threshold Data",
        37:  "Memory Channel",
        38:  "IPMI Device Information",
        39:  "System Power Supply",
        40:  "Additional Information",
        41:  "Onboard Devices Extended Info",
        126: "Inactive",
        127: "End-of-Table",
        130: "Memory SPD Data",
        131: "OEM Processor Type",
        132: "OEM Processor Bus Speed",
    }
    TableSMBIOSMemoryFormFactor* = {
        0: "Reserved",
        1: "Other",
        2: "Unknown",
        3: "SIMM",
        4: "SIP",
        5: "Chip",
        6: "DIP",
        7: "ZIP",
        8: "Proprietary Card",
        9: "DIMM",
        10: "TSOP",
        11: "Row of chips",
        12: "RIMM",
        13: "SODIMM",
        14: "SRIMM",
        15: "FB-DIMM",
    }
    TableSMBIOSMemoryDetails* = {
        0:  "Reserved",
        1:  "Other",
        2:  "Unknown",
        3:  "Fast-paged",
        4:  "Static column",
        5:  "Pseudo-static",
        6:  "RAMBUS",
        7:  "Synchronous",
        8:  "CMOS",
        9:  "EDO",
        10: "Window DRAM",
        11: "Cache DRAM",
        12: "Non-volatile",
        13: "Registered (Buffered)",
        14: "Unbuffered (Unregistered)",
        15: "LRDIMM",
    }
    TableSMBIOSMemoryType* = {
        0x01: "Other",
        0x02: "Unknown",
        0x03: "DRAM",
        0x04: "EDRAM",
        0x05: "VRAM",
        0x06: "SRAM",
        0x07: "RAM",
        0x08: "ROM",
        0x09: "FLASH",
        0x0A: "EEPROM",
        0x0B: "FEPROM",
        0x0C: "EPROM",
        0x0D: "CDRAM",
        0x0E: "3DRAM",
        0x0F: "SDRAM",
        0x10: "SGRAM",
        0x11: "RDRAM",
        0x12: "DDR",
        0x13: "DDR2",
        0x14: "DDR2 FB-DIMM",
        0x15: "RESERVED",
        0x16: "RESERVED",
        0x17: "RESERVED",
        0x18: "DDR3",
        0x19: "FBD2",
        0x1A: "DDR4",
        0x1B: "LPDDR",
        0x1C: "LPDDR2",
        0x1D: "LPDDR3",
        0x1E: "LPDDR4",
    }
    TableSMBMemoryTypeDetails* = {
        0x00: "Reserved",
        0x01: "Other",
        0x02: "Unknown",
        0x03: "Fast-paged",
        0x04: "Static column",
        0x05: "Pseudo-static",
        0x06: "RAMBUS",
        0x07: "Synchronous",
        0x08: "CMOS",
        0x09: "EDO",
        0x0A: "Window DRAM",
        0x0B: "Cache DRAM",
        0x0C: "Non-volatile",
        0x0D: "Registered (Buffered)",
        0x0E: "Unbuffered (Unregistered)",
        0x0F: "LRDIMM",
    }
    TableSMBIOSMemoryArrayLocation* = {
        0x01: "Other",
        0x02: "Unknown",
        0x03: "System board or motherboard",
        0x04: "ISA add-on card",
        0x05: "EISA add-on card",
        0x06: "PCI add-on card",
        0x07: "MCA add-on card",
        0x08: "PCMCIA add-on card",
        0x09: "Proprietary add-on card",
        0x0A: "NuBus",
        0xA0: "PC-98/C20 add-on card",
        0xA1: "PC-98/C24 add-on card",
        0xA2: "PC-98/E add-on card",
        0xA3: "PC-98/Local bus add-on card",
    }
    TableSMBIOSMemoryArrayUse* = {
        0x01: "Other",
        0x02: "Unknown",
        0x03: "System memory",
        0x04: "Video memory",
        0x05: "Flash memory",
        0x06: "Non-volatile RAM",
        0x07: "Cache memory",
    }
    TableSMBIOSMemoryArrayErrorCorrectionTypes* = {
        0x01: "Other",
        0x02: "Unknown",
        0x03: "none",
        0x04: "Parity",
        0x05: "Single-bit ECC",
        0x06: "Multi-bit ECC",
        0x07: "CRC",
    }
    TableSMBIOSMemoryErrorType* = {
        0x01: "Other",
        0x02: "Unknown",
        0x03: "OK",
        0x04: "Bad read",
        0x05: "Parity error",
        0x06: "Single-bit error",
        0x07: "Double-bit error",
        0x08: "Multi-bit error",
        0x09: "Nibble error",
        0x0A: "Checksum error",
        0x0B: "CRC error",
        0x0C: "Corrected single-bit error",
        0x0D: "Corrected error",
        0x0E: "Uncorrectable error",
    }
    TableSMBIOSMemoryErrorGranularity* = {
        0x01: "Other",
        0x02: "Unknown",
        0x03: "Device level",
        0x04: "Memory partition level",
    }
    TableCPUIDFeatures* = {
        0x00: "FPU:Floating-point unit on-chip", # 0 #
        0x01: "VME:Virtual mode extension",
        0x02: "DE:Debugging extension",
        0x03: "PSE:Page size extension",
        0x04: "TSC:Time stamp counter",
        0x05: "MSR:Model specific registers",
        0x06: "PAE:Physical address extension",
        0x07: "MCE:Machine check exception",
        0x08: "CX8:CMPXCHG8 instruction supported",
        0x09: "APIC:On-chip APIC hardware supported",
        
        0x0B: "SEP:Fast system call",
        0x0C: "MTRR:Memory type range registers",
        0x0D: "PGE:Page global enable",
        0x0E: "MCA:Machine check architecture",
        0x0F: "CMOV:Conditional move instruction supported",
        0x10: "PAT:Page attribute table",
        0x11: "PSE-36:36-bit page size extension",
        0x12: "PSN:Processor serial number present and enabled)",
        0x13: "CLFSH:CLFLUSH instruction supported",
        
        0x15: "DS:Debug store",
        0x16: "ACPI:ACPI supported",
        0x17: "MMX:MMX technology supported",
        0x18: "FXSR:FXSAVE and FXSTOR instructions supported",
        0x19: "SSE:Streaming SIMD extensions",
        0x1A: "SSE2:Streaming SIMD extensions 2",
        0x1B: "S:Self-snoop",
        0x1C: "HTT:Multi-threading",
        0x1D: "TM:Thermal monitor supported",
        
        0x1F: "PBE:Pending break enabled",
    }
    TableCacheOperationalMode* = {
        0: "Write Through",
        1: "Write Back",
        2: "ies with Memory Address",
        3: "Unknown",
    }
    TableCacheLocation* = {
        0: "Internal",
        1: "External",
        2: "Reserved",
        3: "Unknown",
    }
    TableSRAMType* = {
        0: "Other",
        1: "Unknown",
        2: "Non-Burst",
        3: "Burst",
        4: "Pipeline Burst",
        5: "Synchronous",
        6: "Asynchronous",
    }
    TableCacheErrorCorrectionType* = {
        1: "Other",
        2: "Unknown",
        3: "None",
        4: "Parity",
        5: "Single-bit ECC",
        6: "Multi-bit ECC",
    }
    TableSystemCachedType* = {
        1: "Other",
        2: "Unknown",
        3: "Instruction",
        4: "Data",
        5: "Unified",
    }
    TableCacheAssociativity* = {
        0x1:  "Other",
        0x2:  "Unknown",
        0x3:  "Direct Mapped",
        0x04: "2-way Set-Associative",
        0x05: "4-way Set-Associative",
        0x06: "Fully Associative",
        0x07: "8-way Set-Associative",
        0x08: "16-way Set-Associative",
        0x09: "12-way Set-Associative",
        0x0A: "24-way Set-Associative",
        0x0B: "32-way Set-Associative",
        0x0C: "48-way Set-Associative",
        0x0D: "64-way Set-Associative",
        0x0E: "20-way Set-Associative",
    }