# SMBIOS tables. See https://www.dmtf.org/sites/default/files/standards/documents/DSP0134_3.4.0.pdf

const
    TableSMBIOSSystemWakeUpReason* = {
        0: "Reserved",
        1: "Other",
        2: "Unknown",
        3: "APM Timer",
        4: "Modem Ring",
        5: "LAN Remote",
        6: "Power Switch",
        7: "PCI PME#",
        8: "AC Power Restored",
    }
    TableSMBIOSDescriptions* = {
        0:   "BIOS Information",
        1:   "System Information",
        2:   "Base Board or Module Information",
        3:   "System Enclosure or Chassis",
        4:   "Processor Information",
        5:   "Memory Controller Information",
        6:   "Memory Module Information",
        7:   "Cache Information",
        8:   "Port Connector Information",
        9:   "System Slots",
        10:  "On Board Devices Information",
        11:  "OEM Strings",
        12:  "System Configuration Options",
        13:  "BIOS Language Information",
        14:  "Group Associations",
        15:  "System Event Log",
        16:  "Physical Memory Array",
        17:  "Memory Device",
        18:  "32-bit Memory Error Information",
        19:  "Memory Array Mapped Address",
        20:  "Memory Device Mapped Address",
        21:  "Built-in Pointing Device",
        22:  "Portable Battery",
        23:  "System Reset",
        24:  "Hardware Security",
        25:  "System Power Controls",
        26:  "Voltage Probe",
        27:  "Cooling Device",
        28:  "Temperature Probe",
        29:  "Electrical Current Probe",
        30:  "Out-of-Band Remote Access",
        31:  "Boot Integrity Services",
        32:  "System Boot Information",
        33:  "64-bit Memory Error Information",
        34:  "Management Device",
        35:  "Management Device Component",
        36:  "Management Device Threshold Data",
        37:  "Memory Channel",
        38:  "IPMI Device Information",
        39:  "System Power Supply",
        40:  "Additional Information",
        41:  "Onboard Devices Extended Info",
        126: "Inactive",
        127: "End-of-Table",
        130: "Memory SPD Data",
        131: "OEM Processor Type",
        132: "OEM Processor Bus Speed",
    }
    TableSMBIOSMemoryFormFactor* = {
        0: "Reserved",
        1: "Other",
        2: "Unknown",
        3: "SIMM",
        4: "SIP",
        5: "Chip",
        6: "DIP",
        7: "ZIP",
        8: "Proprietary Card",
        9: "DIMM",
        10: "TSOP",
        11: "Row of chips",
        12: "RIMM",
        13: "SODIMM",
        14: "SRIMM",
        15: "FB-DIMM",
    }
    TableSMBIOSMemoryDetails* = {
        0:  "Reserved",
        1:  "Other",
        2:  "Unknown",
        3:  "Fast-paged",
        4:  "Static column",
        5:  "Pseudo-static",
        6:  "RAMBUS",
        7:  "Synchronous",
        8:  "CMOS",
        9:  "EDO",
        10: "Window DRAM",
        11: "Cache DRAM",
        12: "Non-volatile",
        13: "Registered (Buffered)",
        14: "Unbuffered (Unregistered)",
        15: "LRDIMM",
    }
    TableSMBIOSMemoryType* = {
        0x01: "Other",
        0x02: "Unknown",
        0x03: "DRAM",
        0x04: "EDRAM",
        0x05: "VRAM",
        0x06: "SRAM",
        0x07: "RAM",
        0x08: "ROM",
        0x09: "FLASH",
        0x0A: "EEPROM",
        0x0B: "FEPROM",
        0x0C: "EPROM",
        0x0D: "CDRAM",
        0x0E: "3DRAM",
        0x0F: "SDRAM",
        0x10: "SGRAM",
        0x11: "RDRAM",
        0x12: "DDR",
        0x13: "DDR2",
        0x14: "DDR2 FB-DIMM",
        0x15: "RESERVED",
        0x16: "RESERVED",
        0x17: "RESERVED",
        0x18: "DDR3",
        0x19: "FBD2",
        0x1A: "DDR4",
        0x1B: "LPDDR",
        0x1C: "LPDDR2",
        0x1D: "LPDDR3",
        0x1E: "LPDDR4",
    }
    TableSMBMemoryTypeDetails* = {
        0x00: "Reserved",
        0x01: "Other",
        0x02: "Unknown",
        0x03: "Fast-paged",
        0x04: "Static column",
        0x05: "Pseudo-static",
        0x06: "RAMBUS",
        0x07: "Synchronous",
        0x08: "CMOS",
        0x09: "EDO",
        0x0A: "Window DRAM",
        0x0B: "Cache DRAM",
        0x0C: "Non-volatile",
        0x0D: "Registered (Buffered)",
        0x0E: "Unbuffered (Unregistered)",
        0x0F: "LRDIMM",
    }
    TableSMBIOSMemoryArrayLocation* = {
        0x01: "Other",
        0x02: "Unknown",
        0x03: "System board or motherboard",
        0x04: "ISA add-on card",
        0x05: "EISA add-on card",
        0x06: "PCI add-on card",
        0x07: "MCA add-on card",
        0x08: "PCMCIA add-on card",
        0x09: "Proprietary add-on card",
        0x0A: "NuBus",
        0xA0: "PC-98/C20 add-on card",
        0xA1: "PC-98/C24 add-on card",
        0xA2: "PC-98/E add-on card",
        0xA3: "PC-98/Local bus add-on card",
    }
    TableSMBIOSMemoryArrayUse* = {
        0x01: "Other",
        0x02: "Unknown",
        0x03: "System memory",
        0x04: "Video memory",
        0x05: "Flash memory",
        0x06: "Non-volatile RAM",
        0x07: "Cache memory",
    }
    TableSMBIOSMemoryArrayErrorCorrectionTypes* = {
        0x01: "Other",
        0x02: "Unknown",
        0x03: "none",
        0x04: "Parity",
        0x05: "Single-bit ECC",
        0x06: "Multi-bit ECC",
        0x07: "CRC",
    }
    TableSMBIOSMemoryErrorType* = {
        0x01: "Other",
        0x02: "Unknown",
        0x03: "OK",
        0x04: "Bad read",
        0x05: "Parity error",
        0x06: "Single-bit error",
        0x07: "Double-bit error",
        0x08: "Multi-bit error",
        0x09: "Nibble error",
        0x0A: "Checksum error",
        0x0B: "CRC error",
        0x0C: "Corrected single-bit error",
        0x0D: "Corrected error",
        0x0E: "Uncorrectable error",
    }
    TableSMBIOSMemoryErrorGranularity* = {
        0x01: "Other",
        0x02: "Unknown",
        0x03: "Device level",
        0x04: "Memory partition level",
    }
    TableSMBIOSMemoryErrorOperationTable* = {
        0x01: "Other",
        0x02: "Unknown",
        0x03: "Read",
        0x04: "Write",
        0x05: "Partial write",
    }
    TableSMBBaseBoardFeaturesTable* = {
        0x00: "Hosting Board",
        0x01: "Requires Daughter Board",
        0x02: "Board is Removable",
        0x03: "Board is Replaceable",
        0x04: "Boar is Hot-Swappable",
    }
    BaseBoardType* = {
        0x01: "Unknown",
        0x02: "Other",
        0x03: "Server Blade",
        0x04: "Connectivity Switch",
        0x05: "System Management Module",
        0x06: "Processor Module",
        0x07: "I/O Module",
        0x08: "Memory Module",
        0x09: "Daughter board",
        0x0A: "Motherboard (includes processor, memory, and I/O)",
        0x0B: "Processor/Memory Module",
        0x0C: "Processor/IO Module",
        0x0D: "Interconnect board",
    }
    TableCPUIDFeatures* = {
        0x00: "FPU:Floating-point unit on-chip", # 0 #
        0x01: "VME:Virtual mode extension",
        0x02: "DE:Debugging extension",
        0x03: "PSE:Page size extension",
        0x04: "TSC:Time stamp counter",
        0x05: "MSR:Model specific registers",
        0x06: "PAE:Physical address extension",
        0x07: "MCE:Machine check exception",
        0x08: "CX8:CMPXCHG8 instruction supported",
        0x09: "APIC:On-chip APIC hardware supported",
        
        0x0B: "SEP:Fast system call",
        0x0C: "MTRR:Memory type range registers",
        0x0D: "PGE:Page global enable",
        0x0E: "MCA:Machine check architecture",
        0x0F: "CMOV:Conditional move instruction supported",
        0x10: "PAT:Page attribute table",
        0x11: "PSE-36:36-bit page size extension",
        0x12: "PSN:Processor serial number present and enabled)",
        0x13: "CLFSH:CLFLUSH instruction supported",
        
        0x15: "DS:Debug store",
        0x16: "ACPI:ACPI supported",
        0x17: "MMX:MMX technology supported",
        0x18: "FXSR:FXSAVE and FXSTOR instructions supported",
        0x19: "SSE:Streaming SIMD extensions",
        0x1A: "SSE2:Streaming SIMD extensions 2",
        0x1B: "S:Self-snoop",
        0x1C: "HTT:Multi-threading",
        0x1D: "TM:Thermal monitor supported",
        
        0x1F: "PBE:Pending break enabled",
    }
    TableProcessorType* = {
        0x01: "Other",
        0x02: "Unknown",
        0x03: "Central Processor",
        0x04: "Math Processor",
        0x05: "DSP Processor",
        0x06: "Video Processor",
    }
    TableProcessorFamily* = {
        0x01: "Other",
        0x02: "Unknown",
        0x03: "8086",
        0x04: "80286",
        0x05: "Intel386TM processor",
        0x06: "Intel486TM processor",
        0x07: "8087",
        0x08: "80287",
        0x09: "80387",
        0x0A: "80487",
        0x0B: "Intel Pentium",
        0x0C: "Intel Pentium Pro",
        0x0D: "Intel Pentium II",
        0x0E: "Intel Pentium MMX",
        0x0F: "Intel Celeron",
        0x10: "Pentium II Xeon",
        0x11: "Pentium III",
        0x12: "M1 Family",
        0x13: "M2 Family",
        0x14: "Intel Celeron M",
        0x15: "Intel Pentium 4 HT",
        # 0x16
        # 0x17
        0x18: "AMD Duron",
        0x19: "K5 Family",
        0x1A: "K6 Family",
        0x1B: "K6-2",
        0x1C: "K6-3",
        0x1D: "AMD Athlon",
        0x1E: "AMD29000",
        0x1F: "K6-2+",
        0x20: "Power PC",
        0x21: "Power PC 601",
        0x22: "Power PC 603",
        0x23: "Power PC 603+",
        0x24: "Power PC 604",
        0x25: "Power PC 620",
        0x26: "Power PC x704",
        0x27: "Power PC 750",
        0x28: "Intel Core Duo",
        0x29: "Intel Core Duo Mobile",
        0x2A: "Intel Core Solo Mobile",
        0x2B: "Intel Atom",
        0x2C: "Intel Core M",
        0x2D: "Intel Core m3",
        0x2E: "Intel Core m5",
        0x2F: "Intel Core m7",
        0x30: "Alpha Family",
        0x31: "Alpha 21064",
        0x32: "Alpha 21066",
        0x33: "Alpha 21164",
        0x34: "Alpha 21164PC",
        0x35: "Alpha 21164a",
        0x36: "Alpha 21264",
        0x37: "Alpha 21364",
        0x38: "AMD Turion II Ultra Dual-Core Mobile M",
        0x39: "AMD Turion II Dual-Core Mobile M",
        0x3A: "AMD Athlon II Dual-Core M",
        0x3B: "AMD Opteron 6100",
        0x3C: "AMD Opteron 4100",
        0x3D: "AMD Opteron 6200",
        0x3E: "AMD Opteron 4200",
        0x3F: "AMD FX",
        0x40: "MIPS",
        0x41: "MIPS R4000",
        0x42: "MIPS R4200",
        0x43: "MIPS R4400",
        0x44: "MIPS R4600",
        0x45: "MIPS R10000",
        0x46: "AMD C-Series",
        0x47: "AMD E-Series",
        0x48: "AMD A-Series",
        0x49: "AMD G-Series",
        0x4A: "AMD Z-Series",
        0x4B: "AMD R-Series",
        0x4C: "AMD Opteron 4300",
        0x4D: "AMD Opteron 6300",
        0x4E: "AMD Opteron 3300",
        0x4F: "AMD FirePro",
        0x50: "SPARC",
        0x51: "SuperSPARC",
        0x52: "MicroSPARC II",
        0x53: "MicroSPARC IIep",
        0x54: "UltraSPARC",
        0x55: "UltraSPARC II",
        0x56: "UltraSPARC IIi",
        0x57: "UltraSPARC III",
        0x58: "UltraSPARC IIIi",
        0x60: "68040",
        0x61: "68xxx",
        0x62: "68000",
        0x63: "68010",
        0x64: "68020",
        0x65: "68030",
        0x66: "AMD Athlon X4",
        0x67: "AMD Opteron X1000",
        0x68: "AMD Opteron X2000",
        0x69: "AMD Opteron A-Series",
        0x6A: "AMD Opteron X3000",
        0x6B: "AMD Zen",
        0x70: "Hobbit",
        0x78: "Crusoe TM5000",
        0x79: "Crusoe TM3000",
        0x7A: "Efficeon TM8000",
        0x80: "Weitek",
        0x82: "Itanium",
        0x83: "AMD Athlon 64",
        0x84: "AMD Opteron",
        0x85: "AMD Sempron",
        0x86: "AMD Turion 64",
        0x87: "AMD Dual-Core Opteron",
        0x88: "AMD Athlon 64 X2",
        0x89: "AMD Turion 64 X2",
        0x8A: "AMD Quad-Core Opteron",
        0x8B: "AMD Third-Generation Opteron",
        0x8C: "AMD Phenom FX",
        0x8D: "AMD Phenom X4",
        0x8E: "AMD Phenom X2",
        0x8F: "AMD Athlon X2",
        0x90: "PA-RISC",
        0x91: "PA-RISC 8500",
        0x92: "PA-RISC 8000",
        0x93: "PA-RISC 7300LC",
        0x94: "PA-RISC 7200",
        0x95: "PA-RISC 7100LC",
        0x96: "PA-RISC 7100",
        0xA0: "V30",
        0xA1: "Intel Quad-Core Xeon 3200",
        0xA2: "Intel Dual-Core Xeon 3000",
        0xA3: "Intel Quad-Core Xeon 5300",
        0xA4: "Intel Dual-Core Xeon 5100",
        0xA5: "Intel Dual-Core Xeon 5000",
        0xA6: "Intel Dual-Core Xeon LV",
        0xA7: "Intel Dual-Core Xeon ULV",
        0xA8: "Intel Dual-Core Xeon 7100",
        0xA9: "Intel Quad-Core Xeon 5400",
        0xAA: "Intel Quad-Core Xeon",
        0xAB: "Intel Dual-Core Xeon 5200",
        0xAC: "Intel Dual-Core Xeon 7200",
        0xAD: "Intel Quad-Core Xeon 7300",
        0xAE: "Intel Quad-Core Xeon 7400",
        0xAF: "Intel Multi-Core Xeon 7400",
        0xB0: "Intel Pentium III Xeon",
        0xB1: "Intel Pentium III Speedstep",
        0xB2: "Intel Pentium 4",
        0xB3: "Intel Xeon",
        0xB4: "AS400",
        0xB5: "Intel Xeon MP",
        0xB6: "Intel Athlon XP",
        0xB7: "Intel Athlon MP",
        0xB8: "Intel Itanium 2",
        0xB9: "Intel Pentium M",
        0xBA: "Intel Celeron D",
        0xBB: "Intel Pentium D",
        0xBC: "Intel Pentium EE",
        0xBD: "Intel Core Solo",
        # 0xBE handled as a special case
        0xBF: "Intel Core 2 Duo",
        0xC0: "Intel Core 2 Solo",
        0xC1: "Intel Core 2 Extreme",
        0xC2: "Intel Core 2 Quad",
        0xC3: "Intel Core 2 Extreme Mobile",
        0xC4: "Intel Core 2 Duo Mobile",
        0xC5: "Intel Core 2 Solo Mobile",
        0xC6: "Intel Core i7",
        0xC7: "Intel Dual-Core Celeron",
        0xC8: "IBM390",
        0xC9: "G4",
        0xCA: "G5",
        0xCB: "ESA/390 G6",
        0xCC: "z/Architecture",
        0xCD: "Intel Core i5",
        0xCE: "Intel Core i3",
        0xCF: "Intel Core i9",
        # ...
        0xD2: "VIA C7-M",
        0xD3: "VIA C7-D",
        0xD4: "VIA C7",
        0xD5: "VIA Eden",
        0xD6: "Intel Multi-Core Xeon",
        0xD7: "Intel Dual-Core Xeon 3xxx",
        0xD8: "Intel Quad-Core Xeon 3xxx",
        0xD9: "VIA Nano",
        0xDA: "Intel Dual-Core Xeon 5xxx",
        0xDB: "Intel Quad-Core Xeon 5xxx",
        # ...
        0xDD: "Intel Dual-Core Xeon 7xxx",
        0xDE: "Intel Quad-Core Xeon 7xxx",
        0xDF: "Intel Multi-Core Xeon 7xxx",
        0xE0: "Intel Multi-Core Xeon 3400",
        # ...
        0xE4: "AMD Opteron 3000",
        0xE5: "AMD Sempron II",
        0xE6: "Embedded AMD Opteron Quad-Core",
        0xE7: "AMD Phenom Triple-Core",
        0xE8: "AMD Turion Ultra Dual-Core Mobile",
        0xE9: "AMD Turion Dual-Core Mobile",
        0xEA: "AMD Athlon Dual-Core",
        0xEB: "AMD Sempron SI",
        0xEC: "AMD Phenom II",
        0xED: "AMD Athlon II",
        0xEE: "AMD Six-Core Opteron",
        0xEF: "AMD Sempron M",
        #...
        0xFA: "i860",
        0xFB: "i960",
        #...
        0x100: "ARMv7",
        0x101: "ARMv8",
        0x104: "SH-3",
        0x105: "SH-4",
        0x118: "ARM",
        0x119: "StrongARM",
        0x12C: "6x86",
        0x12D: "MediaGX",
        0x12E: "MII",
        0x140: "WinChip",
        0x15E: "DSP",
        0x1F4: "Video Processor",
    }
    TableProcessorUpgrade* = {
        0x01: "Other",
        0x02: "Unknown",
        0x03: "Daughter Board",
        0x04: "ZIF Socket",
        0x05: "Replaceable Piggy Back",
        0x06: "None",
        0x07: "LIF Socket",
        0x08: "Slot 1",
        0x09: "Slot 2",
        0x0A: "370-pin socket",
        0x0B: "Slot A",
        0x0C: "Slot M",
        0x0D: "Socket 423",
        0x0E: "Socket A (Socket 462)",
        0x0F: "Socket 478",
        0x10: "Socket 754",
        0x11: "Socket 940",
        0x12: "Socket 939",
        0x13: "Socket mPGA604",
        0x14: "Socket LGA771",
        0x15: "Socket LGA775",
        0x16: "Socket S1",
        0x17: "Socket AM2",
        0x18: "Socket F (1207)",
        0x19: "Socket LGA1366",
        0x1A: "Socket G34",
        0x1B: "Socket AM3",
        0x1C: "Socket C32",
        0x1D: "Socket LGA1156",
        0x1E: "Socket LGA1567",
        0x1F: "Socket PGA988A",
        0x20: "Socket BGA1288",
        0x21: "Socket rPGA988B",
        0x22: "Socket BGA1023",
        0x23: "Socket BGA1224",
        0x24: "Socket LGA1155",
        0x25: "Socket LGA1356",
        0x26: "Socket LGA2011",
        0x27: "Socket FS1",
        0x28: "Socket FS2",
        0x29: "Socket FM1",
        0x2A: "Socket FM2",
        0x2B: "Socket LGA2011-3",
        0x2C: "Socket LGA1356-3",
        0x2D: "Socket LGA1150",
        0x2E: "Socket BGA1168",
        0x2F: "Socket BGA1234",
        0x30: "Socket BGA1364",
        0x31: "Socket AM4",
        0x32: "Socket LGA1151",
        0x33: "Socket BGA1356",
        0x34: "Socket BGA1440",
        0x35: "Socket BGA1515",
        0x36: "Socket LGA3647-1",
        0x37: "Socket SP3",
        0x38: "Socket SP3r2",
        0x39: "Socket LGA2066",
        0x3A: "Socket BGA1392",
        0x3B: "Socket BGA1510",
        0x3C: "Socket BGA1528",
    }
    TableProcessorCharacteristics* = {
        1: "Unknown",
        2: "64-bit Capable",
        3: "Multi-Core",
        4: "Hardware Thread",
        5: "Execute Protection",
        6: "Enhanced Virtualization",
        7: "Power/Performance Control",
    }
    TableCacheOperationalMode* = {
        0: "Write Through",
        1: "Write Back",
        2: "ies with Memory Address",
        3: "Unknown",
    }
    TableCacheLocation* = {
        0: "Internal",
        1: "External",
        2: "Reserved",
        3: "Unknown",
    }
    TableSRAMType* = {
        0: "Other",
        1: "Unknown",
        2: "Non-Burst",
        3: "Burst",
        4: "Pipeline Burst",
        5: "Synchronous",
        6: "Asynchronous",
    }
    TableCacheErrorCorrectionType* = {
        1: "Other",
        2: "Unknown",
        3: "None",
        4: "Parity",
        5: "Single-bit ECC",
        6: "Multi-bit ECC",
    }
    TableSystemCachedType* = {
        1: "Other",
        2: "Unknown",
        3: "Instruction",
        4: "Data",
        5: "Unified",
    }
    TableCacheAssociativity* = {
        0x1:  "Other",
        0x2:  "Unknown",
        0x3:  "Direct Mapped",
        0x04: "2-way Set-Associative",
        0x05: "4-way Set-Associative",
        0x06: "Fully Associative",
        0x07: "8-way Set-Associative",
        0x08: "16-way Set-Associative",
        0x09: "12-way Set-Associative",
        0x0A: "24-way Set-Associative",
        0x0B: "32-way Set-Associative",
        0x0C: "48-way Set-Associative",
        0x0D: "64-way Set-Associative",
        0x0E: "20-way Set-Associative",
    }